name: ai_chatbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  google_generative_ai: ^0.4.0
  http: ^1.2.1
  image_picker: ^1.1.1
  langchain: ^0.7.1
  langchain_community: ^0.2.0+1
  langchain_google: ^0.5.0
  sizer: ^2.0.15
  syncfusion_flutter_pdf: ^25.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
